---
- name: Updating Network Plugin to {{ openshift_network_plugin_type }} on Master
  yedit:
    src: '{{ item }}'
    key: networkConfig.networkPluginName
    value: '{{ openshift_network_plugin_type }}'
    state: present
    backup: yes
  with_items: '{{ openshift_network_plugin_master_config }}'

- import_role:
    name: common
    tasks_from: restart-master.yaml