---

- import_role:
    name: common
    tasks_from: ansible-fact.yaml
  when: backup_prefix is undefined
  tags: always

- name: Ensure snapshot Etcd script is installed
  copy:
    src: '{{ item }}'
    dest: '/usr/local/bin/{{ item }}'
    owner: root
    group: root
    mode: 0750
  with_items:
    - etcd-snapshot.sh

- name: Ensure directory etcd backup exist
  file:
    path: '{{ etcd_backup_root }}'
    state: directory

- name: Ensure etcd package is installed
  yum:
    name: etcd
    state: present

- name: Running etcd data snapshot script [/usr/local/bin/etcd-snapshot.sh {{ etcd_backup_root }}]
  shell: |
    /usr/local/bin/etcd-snapshot.sh {{ etcd_backup_root }}

- name: Backup etcd backup files
  archive:
    dest: '{{ etcd_backup_root }}/etcd.tar'
    path:
      - '{{ etcd_backup_root }}/db'
      - '{{ etcd_backup_root }}/status'

- name: Fetch snapshot and status
  fetch:
    src: '{{ etcd_backup_root }}/etcd.tar'
    dest: '{{ etcd_backup_root }}/{{ backup_prefix }}/{{ ansible_fqdn }}/'
    flat: true
    fail_on_missing: yes
