---
- name: Enable ExpandPersistenVolumes on Node
  yedit:
    src: '{{ openshift_local_volume_node_config }}'
    key: kubeletArguments.feature-gates
    value:
    - PersistentLocalVolumes=true
    state: present
    backup: yes

- name: Enable VolumeScheduling on Node
  yedit:
    src: '{{ openshift_local_volume_node_config }}'
    key: kubeletArguments.feature-gates
    value:
    - VolumeScheduling=true
    state: present
    backup: yes

- name:  Restart Node
  service:
    name: atomic-openshift-node
    state: restarted
