---

- hosts: OSEv3
  vars:
    - backup_root: /backup
#   - s3_backup_bucket:
#   - aws_region:
#   - backup_prefix:

  roles:
    - role: backup

  post_tasks:
    - name: Sync backup to s3 bucket
      s3_sync:
        bucket: '{{ s3_backup_bucket }}'
        region: '{{ aws_region }}'
        key_prefix: '{{ backup_prefix }}/'
        file_root: '{{ backup_root }}/{{ backup_prefix }}/'
        mode: push
        permission: private
        file_change_strategy: date_size
      delegate_to: localhost
      run_once: true
      tags: s3_sync

    - import_role:
        name: backup
        tasks_from: cleanup.yaml
      tags:
        - s3_sync
        - cleanup